
version: '3.9'

services:
  app:
    build: .
    image: php:8.2-apache
    container_name: meu_app
    ports:
      - "8080:80"
    volumes:
   
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: meu_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASS}
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
      MYSQL_USER: ${MYSQL_USER_NAME}
      MYSQL_PASSWORD: ${MYSQL_USER_PASS}
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./banco.sql:/docker-entrypoint-initdb.d/banco.sql


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: meu_pma
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASS}
    ports:
      - "8081:80"
    depends_on:
      - db

volumes:
  db_data: